contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    # contact.user urls
    path("user/register/", views.register, name="register"),
    path("user/login/", views.login_view, name="login"),
    path("user/logout/", views.logout_view, name="logout"),
    path("user/update/", views.user_update, name="user_update"),

    # contact.forms urls
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    # contact.views urls
    path('<int:contact_id>/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'{self.name}'

class Contact(models.Model):
    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    first_name = models.CharField(max_length=50, verbose_name='Nome')
    last_name = models.CharField(max_length=50, verbose_name='Sobrenome')
    phone = models.CharField(max_length=50, verbose_name='Telefone')
    email = models.EmailField(max_length=50, verbose_name='E-mail')
    created_date = models.DateTimeField(default=timezone.now, verbose_name="Criado em")
    description = models.TextField(blank=True, verbose_name='Descrição',)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/Ym/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Categoria',
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    def __str__(self) -> str:
        return f'{self.pk} {self.first_name} {self.last_name}'

contact/forms.py
from typing import Any
from django import forms
from contact import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation

class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        label='Nome',
        min_length=5,
        required=True,
        help_text='Requerido',
    )
    last_name = forms.CharField(
        label='Sobrenome',
        min_length=5,
        required=True,
        help_text='Requerido',
    )
    email = forms.EmailField(
        label='email',
        min_length=5,
        required=True,
        help_text='Requerido',
    )
    username = forms.CharField(
        label='Usuário',
        min_length=5,
        required=True,
        help_text='Requerido',
    )
    password1 = forms.CharField(
        label='Senha',
        strip=False,
        required=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
            },
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Confirmar senha',
        strip=False,
        required=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
            },
        ),
        help_text='Use a mesma a senha do primeiro campo.',
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')
        if password:
            user.set_password(password)

        if commit:
            user.save()
        
        return user

    def clean(self) -> dict[str, Any]:
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError(
                        'As senhas devem ser iguais.',
                        code='invalid',
                    )
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email
        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError(
                        'Este email já existe',
                        code='invalid',
                    )
                )
            return email
        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(
                        errors,
                        code='invalid',
                    )
                )
        return password1

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=5,
        label='Nome',
        help_text='Requerido',
    )
    last_name = forms.CharField(
        required=True,
        min_length=5,
        label='Sobrenome',
        help_text='Requeido',
    )
    email = forms.EmailField(
        required=True,
        label='E-mail',
        help_text='requerido',
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError(
                    'Este email já existe',
                    code='invalid',
                )
            )
        return email

class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        label='Imagem',
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            },
        ),
        required=False,
    )

    class Meta:
        model = models.Contact
        fields = ('first_name', 'last_name', 'phone',
                  'email', 'description', 'category', 'picture',)

contact/views.py
from django.shortcuts import render

def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/forms_contact.py
from contact import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from contact import models
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required(login_url='contact:login')
def create(request):
    form = forms.ContactForm()
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = forms.ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'site_title': 'Criar contato -',
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            messages.success(request, 'Contato criado com sucesso!')
            return redirect('contact:update', contact_id=contact.id)

        return render(
            request,
            'contact/create.html',
            context,
        )

    context = {
        'form': form,
        'site_title': 'Criar contato -',
        'form_action': form_action,
    }
    return render(
        request,
        'contact/create.html',
        context,
    )

@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(models.Contact.objects, pk=contact_id, show=True, owner=request.user)
    form_action = reverse('contact:update', args=(contact_id, ))
    form = forms.ContactForm(instance=contact)

    if request.method == 'POST':
        form = forms.ContactForm(request.POST, request.FILES, instance=contact)
        context = {
            'form': form,
            'site_title': 'Atualizar contato -',
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save()
            messages.success(request, 'Contato atualizado!')
            return redirect('contact:update', contact_id=contact.id)
        messages.error(request, 'Verifique os dados do contato!')

        return render(
            request,
            'contact/create.html',
            context,
        )

    context = {
        'form': form,
        'site_title': 'Atualizar contato -',
        'form_action': form_action,
    }
    
    return render(
        request,
        'contact/create.html',
        context,
    )

@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(models.Contact.objects, pk=contact_id, show=True, owner=request.user)
    confirmation = request.POST.get('confirmation', 'no')
    context = {
        'contact': contact,
        'confirmation': confirmation,
        'site_title': 'Deletar contato -'
    }
    if confirmation == 'yes':
        contact.delete()
        messages.success(request, 'Contato deletado!')
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        context,
    )

contact/views/user_forms.py
from django.shortcuts import render, redirect
from django.contrib import messages
from contact import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import auth

def register(request):
    form = forms.RegisterForm()
    if request.method == 'POST':
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário registrado!')
            return redirect('contact:login')
        messages.error('Verifique os dados do usuário!')
    
    context = {
        'site_title': 'Registrar -',
        'form': form,
    }

    return render(
        request,
        'contact/register.html',
        context,
    )

def login_view(request):
    form = AuthenticationForm(request)
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user=user)
            messages.success(request, 'Você entrou =)')
            return redirect('contact:index')
        messages.error(request, 'Login inválido!')

    context = {
        'site_title': 'Autenticação -',
        'form': form,
    }

    return render(
        request,
        'contact/login.html',
        context,
    )

@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    messages.success(request, 'Você saiu =)')
    return redirect('contact:login')

@login_required(login_url='contact:login')
def user_update(request):
    form = forms.UserUpdateForm(instance=request.user)
    if request.method == 'POST':
        form = forms.UserUpdateForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário atualizado!')
            return redirect('contact:user_update')

    context = {
        'site_title': 'Sua conta -',
        'form': form,
    }

    return render(
        request,
        'contact/register.html',
        context,
    )

contact/views/views_contact.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from contact import models
from django.contrib import messages

def index(request):
    contacts = models.Contact.objects.filter(show=True).order_by('-id')
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos -'
    }
    return render(
        request,
        'contact/index.html',
        context,
    )

def contact(request, contact_id):
    single_contact = get_object_or_404(models.Contact.objects, pk=contact_id, show=True)
    site_title = f'{single_contact.first_name} {single_contact.last_name} -'
    context = {
        'contact': single_contact,
        'site_title': site_title,
    }
    return render(
        request,
        'contact/contact.html',
        context
    )

def search(request):
    search_value = request.GET.get('q', '').strip()
    search_context = f'Busca por "{search_value}" -'
    if search_value == '':
        messages.info(request, 'Você não buscou por nada!')
        return redirect('contact:index')
    
    contacts = models.Contact.objects.filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value),
        show=True,
    ).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': search_context,
        'search_value': search_value,
    }

    return render(
        request,
        'contact/index.html',
        context,
    )

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">{{contact.first_name}} {{contact.last_name}}</h1>

        <p><b>ID: </b>{{contact.id}}</p>
        <p><b>Telefone: </b>{{contact.phone}}</p>
        <p><b>E-mail: </b>{{contact.email}}</p>
        <p><b>Criado em: </b>{{contact.created_date}}</p>
        <p><b>Descrição: </b>{{contact.description}}</p>
        <p><b>Categoria: </b>{{contact.category.name}}</p>
        {% if contact.picture %}
            <p>
                <img src="{{contact.picture.url}}" alt="{{contact.first_name}} {{contact.last_name}}">
            </p>
        {% endif %}

        {% if user == contact.owner %}
            <div class="contact-links">
                <a href="{% url "contact:update" contact.id %}" class="btn btn-link">Atualizar</a>
                <form action="{% url "contact:delete" contact.id %}" method="POST">
                    {% csrf_token %}
                    {% if confirmation == 'no' %}
                        <input type="hidden" name="confirmation" value="yes">
                        <button class="btn btn-link btn-delete" type="submit">Confirmar?</button>
                    {% else %}
                        <button class="btn btn-link btn-delete" type="submit">Deletar</button>
                    {% endif %}
                </form>
            </div>
        {% endif %}
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        <h2>Contato</h2>
        <form
        action="{{form_action}}"
        method="POST"
        enctype="multipart/form-data"
        >
        {% csrf_token %}
            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                        {{field.errors}}
                    </div>

                    {% if field.name == 'picture' and field.value.url %}
                        <div class="form-group">
                            <img src="{{field.value.url}}" alt="{{field.first_name}} {{field.last_name}}">
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Enviar</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
    {% if page_obj %}
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contatos
                </caption>

                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">Nome</th>
                        <th class="table-header">Sobrenome</th>
                        <th class="table-header">Telefone</th>
                        <th class="table-header">Email</th>
                    </tr>
                </thead>

                <tbody>
                    {% for contact in page_obj %}
                        <tr class="table-row">
                            <td class="table-cel">
                                <a href="{% url "contact:contact" contact.id%}"
                                class="table-link">{{contact.id}}</a>
                            </td>
                            <td class="table-cel">{{contact.first_name}}</td>
                            <td class="table-cel">{{contact.last_name}}</td>
                            <td class="table-cel">{{contact.phone}}</td>
                            <td class="table-cel">{{contact.email}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">Nenhum contato encontrado.</h1>
        </div>
    {% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        {% if user.is_authenticated %}
            <p>
                <h2>Deslogar</h2>
                Você esta logado como {{user.username}}. <br>
                Clique <a href="{% url "contact:logout" %}">aqui </a>para deslogar.
            </p>
        {% else %}
            <h2>Logar</h2>
            {% include "contact/partials/_user-form.html" %}
        {% endif %}

    </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        <h2>Registrar</h2>
        {% include "contact/partials/_user-form.html" %}

    </div>
{% endblock content %}